language: ruby
rvm:
- 2.1.1
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  slack:
    secure: i6ttgSutpMHML06+FwNhQN+X0eDDAMf/WAuhnKWa1FwB2WTfzCIrNv3rKHWB69RG2Kd1fd62MNs9U6iO0fNvbTwe/CrgQyRg5xznxeOOw2c7cSVJYr8ktOF4C2vAIfGTZ/pqJoVzhWaGbzLFH0l+l6iLPI2gfr6kjychcv2kmmA=
